name: woocommerce_api
description: A package to interact with the WooCommerce API (null-safe).
version: 0.1.0
author: Samarth Agarwal <samarthagarwal@live.com>
homepage: https://github.com/samarthagarwal/woocommerce_dart

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

environment:
  sdk: ">=2.12.0 <3.0.0"